import { nanoid } from "nanoid";

export const dataFoods = [
  {
    id: nanoid(),
    name: "Artischocke",
    category: "Gemüse",
    availability: ["Juli", "August", "September"],
    img: "/food-images/artichoke.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Aubergine",
    category: "Gemüse",
    availability: ["Juni", "Juli", "August", "September", "Oktober"],
    img: "/food-images/eggplant.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Blumenkohl",
    category: "Gemüse",
    availability: ["Mai", "Juni", "Juli", "August", "September", "November"],
    img: "/food-images/cauliflower.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Bohnen (grün)",
    category: "Gemüse",
    availability: ["Juni", "Juli", "August"],
    img: "/food-images/green-beans.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Brokkoli",
    category: "Gemüse",
    availability: [
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
    ],
    img: "/food-images/brocoli.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Butternut-Kürbis",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/butternut.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Champignon",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/champignon.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Chinakohl",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/chinese-cabbage.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Erbse",
    category: "Gemüse",
    availability: ["Juni", "Juli", "August"],
    img: "/food-images/pea.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Fenchel",
    category: "Gemüse",
    availability: ["Juni", "Juli", "August", "September", "Oktober"],
    img: "/food-images/fennel.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Frühlings-Zwiebel",
    category: "Gemüse",
    availability: ["Mai", "Juni", "Juli", "August", "September", "Oktober"],
    img: "/food-images/spring-onion.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Grünkohl",
    category: "Gemüse",
    availability: ["Januar", "Oktober", "November", "Dezember"],
    img: "/food-images/kale.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Hokkaido",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/hokkaido.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Kartoffel",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/potatoe.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Knollensellerie",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/celery-root.png",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Kohlrabi",
    category: "Gemüse",
    availability: ["Mai", "Juni", "Juli", "August", "September", "Oktober"],
    img: "/food-images/kohlrabi.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Kürbis",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/pumpkin.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Mairübe",
    category: "Gemüse",
    availability: ["Mai", "Juni", "Juli"],
    img: "/food-images/mairuebe.jpeg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Mais",
    category: "Gemüse",
    availability: ["Juli", "August", "September", "Oktober"],
    img: "/food-images/corn.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Mangold",
    category: "Gemüse",
    availability: ["Mai", "Juni", "Juli", "August", "September", "Oktober"],
    img: "/food-images/chard.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Meerrettich",
    category: "Gemüse",
    availability: ["Januar", "Oktober", "November", "Dezember"],
    img: "/food-images/horseradish.jpeg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Möhre",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/carrot.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Pak Choi",
    category: "Gemüse",
    availability: ["Mai", "Juni", "Juli", "August", "September", "Oktober"],
    img: "/food-images/pak-choi.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Paprikaschote",
    category: "Gemüse",
    availability: ["Juni", "Juli", "August", "September", "Oktober"],
    img: "/food-images/pepper.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Pastinake",
    category: "Gemüse",
    availability: ["Januar", "Februar", "November", "Dezember"],
    img: "/food-images/parsnip.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Petersilien-Wurzel",
    category: "Gemüse",
    availability: ["Januar", "Februar", "November", "Dezember"],
    img: "/food-images/parsley-root.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Pfifferling",
    category: "Gemüse",
    availability: ["Juli", "August"],
    img: "/food-images/chanterelle.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Porree",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/leek.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Radieschen",
    category: "Gemüse",
    availability: [
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
    ],
    img: "/food-images/radish.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Rettich",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/rettich.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Rhabarber",
    category: "Gemüse",
    availability: ["März", "April", "Mai", "Juni", "Juli"],
    img: "/food-images/rhubarb.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Romanesco",
    category: "Gemüse",
    availability: ["Mai", "Juni", "Juli", "August", "September", "Oktober"],
    img: "/food-images/romanesco.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Rosenkohl",
    category: "Gemüse",
    availability: ["Januar", "Oktober", "November", "Dezember"],
    img: "/food-images/brussels-sprouts.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Rote Bete",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/beetroot.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Rotkohl",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/red-cabbage.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Salatgurke",
    category: "Gemüse",
    availability: ["Mai", "Juni", "Juli", "August"],
    img: "/food-images/cucumber.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Schalotte",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/shallot.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Spaghetti-Kürbis",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/spaghetti-squash.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Spargel",
    category: "Gemüse",
    availability: ["Mai", "Juni"],
    img: "/food-images/asparagus.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Spinat",
    category: "Gemüse",
    availability: [
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
    ],
    img: "/food-images/spinach.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Spitzkohl",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/spitzkohl.jpeg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Staudensellerie",
    category: "Gemüse",
    availability: ["Juni", "Juli", "August", "September", "Oktober"],
    img: "/food-images/celery.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Steckrübe",
    category: "Gemüse",
    availability: ["Januar", "Februar", "November", "Dezember"],
    img: "/food-images/turnip.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Steinpilz",
    category: "Gemüse",
    availability: ["August", "September", "Oktober"],
    img: "/food-images/mushroom.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Süßkartoffel",
    category: "Gemüse",
    availability: ["September", "Oktober"],
    img: "/food-images/sweet-potato.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Tomate",
    category: "Gemüse",
    availability: ["Juli", "August", "September"],
    img: "/food-images/tomato.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Weißkohl",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/white-cabbage.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Wirsing",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/savoy.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Zucchini",
    category: "Gemüse",
    availability: ["Juni", "Juli", "August", "September"],
    img: "/food-images/zucchini.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Zwiebel",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/onion.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Apfel",
    category: "Obst",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/apple.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Aprikose",
    category: "Obst",
    availability: ["Juli", "August"],
    img: "/food-images/apricot.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Birne",
    category: "Obst",
    availability: [
      "Januar",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "/food-images/pear.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Brombeere",
    category: "Obst",
    availability: ["Juli", "August", "September"],
    img: "/food-images/blackberry.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Erdbeere",
    category: "Obst",
    availability: ["Mai", "Juni", "Juli"],
    img: "/food-images/strawberry.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Hagebutte",
    category: "Obst",
    availability: ["September", "Oktober", "November", "Dezember"],
    img: "/food-images/rose-hip.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Heidelbeere",
    category: "Obst",
    availability: ["Juni", "Juli", "August", "September"],
    img: "/food-images/blueberry.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Himbeere",
    category: "Obst",
    availability: ["Juni", "Juli", "August", "September"],
    img: "/food-images/raspberry.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Holunderbeere",
    category: "Obst",
    availability: ["August", "September"],
    img: "/food-images/elderberry.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Johannisbeere",
    category: "Obst",
    availability: ["Juni", "Juli", "August"],
    img: "/food-images/currant.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Kirsche",
    category: "Obst",
    availability: ["Juni", "Juli", "August"],
    img: "/food-images/cherry.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Maulbeere",
    category: "Obst",
    availability: ["Juli", "August"],
    img: "/food-images/mulberry.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Mirabelle",
    category: "Obst",
    availability: ["Juli", "August", "September"],
    img: "/food-images/mirabelle.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Nektarine",
    category: "Obst",
    availability: ["Juli", "August", "September"],
    img: "/food-images/nectarine.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Pfirsich",
    category: "Obst",
    availability: ["Juli", "August", "September"],
    img: "/food-images/peach.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Pflaume",
    category: "Obst",
    availability: ["Juni", "Juli", "August", "September"],
    img: "/food-images/plum.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Quitte",
    category: "Obst",
    availability: ["Oktober", "November"],
    img: "/food-images/quince.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Stachelbeere",
    category: "Obst",
    availability: ["Juni", "Juli", "August"],
    img: "/food-images/gooseberry.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Wassermelone",
    category: "Obst",
    availability: ["August", "September"],
    img: "/food-images/watermelon.svg",
    isFavorite: false,
  },

  {
    id: nanoid(),
    name: "Weintraube",
    category: "Obst",
    availability: ["September", "Oktober"],
    img: "/food-images/grape.svg",
    isFavorite: false,
  },
];
