export const dataFoods = [
  {
    id: 1,
    name: "Artischocke",
    category: "Gemüse",
    availability: ["Juli", "August", "September"],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },

  {
    id: 2,
    name: "Aubergine",
    category: "Gemüse",
    availability: ["Juni", "Juli", "August", "September", "Oktober"],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },

  {
    id: 3,
    name: "Blumenkohl",
    category: "Gemüse",
    availability: ["Mai", "Juni", "Juli", "August", "September", "November"],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },
  {
    id: 4,
    name: "Brokkoli",
    category: "Gemüse",
    availability: [
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
    ],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },

  {
    id: 5,
    name: "Champignon",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },

  {
    id: 6,
    name: "Erbse",
    category: "Gemüse",
    availability: ["Juni", "Juli", "August"],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },
  {
    id: 7,
    name: "Fenchel",
    category: "Gemüse",
    availability: ["Juni", "Juli", "August", "September", "Oktober"],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },
  {
    id: 8,
    name: "Frühlings-zwiebel",
    category: "Gemüse",
    availability: ["Mai", "Juni", "Juli", "August", "September", "Oktober"],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },
  {
    id: 9,
    name: "Grünkohl",
    category: "Gemüse",
    availability: ["Januar", "Oktober", "November", "Dezember"],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },
  {
    id: 10,
    name: "Butternut-Kürbis",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "März",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },
  {
    id: 11,
    name: "Hokkaido",
    category: "Gemüse",
    availability: [
      "Januar",
      "Februar",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },
  {
    id: 12,
    name: "Himbeere",
    category: "Obst",
    availability: ["Juni", "Juli", "August", "September"],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },
  {
    id: 13,
    name: "Apfel",
    category: "Obst",
    availability: [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember",
    ],
    img: "https://res.cloudinary.com/ds8jsfspm/image/upload/v1670943393/foods/Download_qzuaij.jpg",
    isFavorite: false,
  },
];
